# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 070eda1b00dce196f4ed308cbcab15d1790a22cebe0218903d0aab48b159503a949086b007ac445a221f4443bc0327af0e7e8adaf6fd54bd36471f961ee63adb

test:
  secret_key_base: b1cdd0db6a2580c1692959d19dbc8946883fe2340541178c6cbbc587e30014353689c7d41e85abc671a1274ad8b4819f947508e3fe065726776b38deb52fe130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
